### PR TITLE
Fix no-global-jquery returning false positive for var assignment #85

### LINKED ISSUE #85: 'no-global-jquery' flags false positive when Ember.$ assigned to a var
```js
const $ = Ember.$;
$.whatever(); // flags '$'
```

### PR DESCRIPTION
**Pull request by nlfurniss**
```js
// This currently fails
const $ = Ember.$;
$(...); // flagged as global jQuery
```

this PR:
* Fixes #85 
* adds tests
* moves the following logic to util
  * logic to determine if jQuery is the callee
  * array if jquery aliases
  * function to determine if variable assignment is jQuery

### CODE REVIEW

File: lib/rules/no-global-jquery.js [hunk 1]
```diff
@@ -48,8 +53,14 @@ module.exports = {
         }
       },
 
+      VariableDeclarator(node) {
+        jQueryLocalName = isVariableAssigmentJquery(node);
```
Comment (rwjblue) [inline lib/rules/no-global-jquery.js]: Doesn't this clobber `jQueryLocalName` for every variable declaration?

Specifically, wouldn't the following have `jQueryLocalName` be `null` in the following example?

```js
let a = jQuery;
let b = 'lolwut';

a('.find-me').click();
```

I may be wrong about ^ though. Either way, could you add a test that shows this properly identifying the `a` usage?

File: lib/utils/jquery.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
+const { get } = require('../utils/get');
+
+const JQUERY_ALIASES = ['$', 'jQuery'];
+
+function isJQueryCallee(node, name = null) {
+  const calleePropertyNameisJquery = get(node, 'object.callee.property.name') === '$';
```
Comment (rwjblue) [inline lib/utils/jquery.js]: I think these should use `JQUERY_ALIASES` (instead of hard coding to `$`).

Something like:

```js
const calleePropertyNameisJquery = JQUERY_ALIASES.includes(get(node, 'object.callee.property.name'));
```

File: lib/rules/no-global-jquery.js (hunk 1 above)
Comment (nlfurniss) [reply lib/rules/no-global-jquery.js]: Yup, this fails in master. Added passing test in new commit

File: lib/utils/jquery.js (hunk 2 above)
Comment (nlfurniss) [reply lib/utils/jquery.js]: Done

**Comment by nlfurniss** [comment]
@rwjblue I cleaned up the logic for variable declarations, but I wanted to discuss whether it's worth catching the edge-case of `const $ = Ember.$;`

It makes the code quite a bit more complicated ([as you can see here](https://gist.github.com/nlfurniss/f92d1458fa55408b966e95a4f1a4336c)). It's not easy to figure out what an identifier is with static analysis 😝

**Comment by nlfurniss** [comment]
OK after doing some rethinking/refactoring, I can fix the false positives without all that code.

File: lib/rules/no-global-jquery.js [hunk 3]
```diff
@@ -48,8 +52,18 @@ module.exports = {
...
+        } else {
+          const varName = get(node, 'id.name');
+          emberJqueryVariables.push(varName);
+        }
+      },
+
       CallExpression(node) {
-        if (!isDestructured(node) && isGlobalJquery(node)) {
+        const calleeName = get(node, 'callee.name');
+        if (!isDestructured(node) && isGlobalJquery(node) && !emberJqueryVariables.includes(calleeName)) {
```
Comment (rwjblue) [inline lib/rules/no-global-jquery.js]: Just to clarify, the point of `emberJqueryVariables` is to avoid issuing an error when a local variable was used (and therefore it no longer falls under this particular rule).  Is that correct?

File: lib/rules/no-jquery-methods.js [hunk 4]
```diff
@@ -52,23 +40,14 @@ module.exports = {
...
-          || get(node, 'init.property.name')
-          || get(node, 'init.name')
-          || '';
-        const varAssignmentIsJquery = JQUERY_ALIASES.includes(varAssignment);
-
-        if (varAssignmentIsJquery) {
-          jQueryLocalName = varDecIDName;
-        }
+        const varName = get(node, 'id.name');
+        jQueryLocalName = isVariableAssigmentJquery(node) ? varName : null;
```
Comment (rwjblue) [inline lib/rules/no-jquery-methods.js]: This still only allows a single local for jQuery right?

E.g. given this snippet:

```js
import jQ from 'jquery';
const dolla = Ember.$;

dolla('.foo').focus();
jQ('.derp').focus();
```

We would only consider `dolla('.foo').focus()` incorrect (because the `const jQ = Ember.$` assignment happens and resets `jQueryLocalName`).

File: lib/rules/no-global-jquery.js (hunk 3 above)
Comment (nlfurniss) [reply lib/rules/no-global-jquery.js]: `emberJqueryVariables` is meant to collection things like `const $ = Ember.$`: variables with names that would otherwise trigger the rule (`$`, `jQuery`), but are actually safe.

File: lib/rules/no-jquery-methods.js (hunk 4 above)
Comment (nlfurniss) [reply lib/rules/no-jquery-methods.js]: Yes, I was originally only trying to solve for the `no-global-jquery` case, but it makes to fix this behavior here too

**Comment by nlfurniss** [comment]
Note: would like to squash these commits before merging

File: lib/rules/no-global-jquery.js (hunk 3 above)
Comment (rwjblue) [reply lib/rules/no-global-jquery.js]: perfect, thanks for confirming
